config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('core.urls'), name='core')
]

core/urls.py
from importlib.machinery import ExtensionFileLoader
from django.urls import path
from . import views


app_name = 'core'

urlpatterns = [
    path("", views.index_view, name='index'),
    path("topicos/", views.topicos_view, name='topicos'),
    path("edita_topicos", views.edita_topicos_view, name='edita_topicos'),
    path("novo_topico/", views.novo_topico_view, name='novo_topico'),
    path("edita_topico/<int:topico_id>", views.edita_topico_view, name='edita_topico'),
    path("apaga_topico/<int:topico_id>", views.apaga_topico_view, name='apaga_topico'),
    path("novo_conteudo/", views.novo_conteudo_view, name='novo_conteudo'),
    path("edita_conteudo/<int:conteudo_id>", views.edita_conteudo_view, name='edita_conteudo'),
    path("apaga_conteudo/<int:conteudo_id>", views.apaga_conteudo_view, name='apaga_conteudo'),
]

core/models.py
from django.db import models

# Create your models here.
class Topico(models.Model):
    nome = models.CharField(max_length=50)
    ordem = models.IntegerField()

    def __str__(self):
        return f'{self.ordem}. {self.nome}'

class Conteudo(models.Model):
    descricao = models.CharField(max_length=200)
    ordem = models.IntegerField()
    topico = models.ForeignKey(Topico, related_name='conteudos', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.descricao}'


        

core/forms.py
from django.forms import ModelForm
from .models import Topico, Conteudo


class TopicoForm(ModelForm):
    class Meta:
        model = Topico
        fields = '__all__'


class ConteudoForm(ModelForm):
    class Meta:
        model = Conteudo
        fields = '__all__'

core/views.py
from django.shortcuts import redirect, render
from .models import Topico, Conteudo
from .forms import TopicoForm, ConteudoForm

# Create your views here.
def index_view(request):
    return render(request, 'core/index.html')


def topicos_view(request):

    topicos = Topico.objects.all().order_by('ordem')

    context = {
        'topicos':topicos
    }

    return render(request, 'core/topicos.html', context)


def edita_topicos_view(request):

    topicos = Topico.objects.all().order_by('ordem')

    context = {
        'topicos':topicos
    }

    return render(request, 'core/edita_topicos.html', context)


def novo_topico_view(request):

    topico_form = TopicoForm(request.POST or None)
    if topico_form.is_valid():
        topico_form.save()
        return redirect('core:edita_topicos')

    context = {'topico_form':topico_form}
    return render(request, 'core/novo_topico.html', context)


def edita_topico_view(request, topico_id):

    topico = Topico.objects.get(id=topico_id)
    topico_form = TopicoForm(request.POST or None, instance=topico)
    if request.method == "POST" and topico_form.is_valid():
        topico_form.save()
        return redirect('core:edita_topicos')

    context = {'topico_form':topico_form, 'topico_id':topico_id}
    return render(request, 'core/edita_topico.html', context)


def apaga_topico_view(request, topico_id):
    topico = Topico.objects.get(id=topico_id)
    topico.delete()
    return redirect('core:edita_topicos')


def novo_conteudo_view(request):

    conteudo_form = ConteudoForm(request.POST or None)
    if conteudo_form.is_valid():
        conteudo_form.save()
        return redirect('core:edita_topicos')

    context = {'conteudo_form':conteudo_form}
    return render(request, 'core/novo_conteudo.html', context)


def edita_conteudo_view(request, conteudo_id):

    conteudo = Conteudo.objects.get(id=conteudo_id)
    conteudo_form = ConteudoForm(request.POST or None, instance=conteudo)
    if request.method == "POST" and conteudo_form.is_valid():
        conteudo_form.save()
        return redirect('core:edita_topicos')

    context = {'conteudo_form':conteudo_form, 'conteudo_id':conteudo_id}
    return render(request, 'core/edita_conteudo.html', context)


def apaga_conteudo_view(request, conteudo_id):
    conteudo = Conteudo.objects.get(id=conteudo_id)
    conteudo.delete()
    return redirect('core:edita_topicos')

templates/core/edita_conteudo.html
{% extends "layout.html" %}

{% block main %}

    <h3>Edita Conteúdo</h3>

<form action=" {% url 'core:edita_conteudo' conteudo_id %}" method="POST">
    {% csrf_token %}

    <table>
        {{conteudo_form}}
    </table>
    <div class="botoes">
        <a href="{% url 'core:apaga_conteudo' conteudo_id %}" class="btn btn-outline-danger btn-sm">Apagar</a>    
        <input type="submit" value="Guardar" class="btn btn-primary btn-sm">
    </div>    
</form>

{% endblock main %}

</body>

</html>

templates/core/edita_topico.html
{% extends "layout.html" %}

{% block main %}

    <h3>Edita Tópico</h3>

<form action="{% url 'core:edita_topico' topico_id %}" method="POST">
    {% csrf_token %}

    <table>
        {{topico_form}}
    </table>
    
    <input type="submit" class="btn btn-success  btn-sm" value="Guardar">
    <a href="{% url 'core:apaga_topico' topico_id %}" class="btn btn-outline-danger btn-sm">Apagar</a>
</form>

{% endblock main %}

</body>

</html>

templates/core/edita_topicos.html
{% extends "layout.html" %}

{% block main %}

<h3>Tópicos abordados</h3>

{% load custom_tags %}

{% for topico in topicos  %}

<h5>{{ topico }} <a href="{% url 'core:edita_topico' topico.id %}" class="btn btn-outline-primary  btn-sm"  style="padding:0 1ch" >Editar</a> </h5>

    {% for conteudo in topico.conteudos.all|sort_by:'ordem' %}
    <div class="conteudo"> {{ conteudo }}  <a href="{% url 'core:edita_conteudo' conteudo.id %}" class="btn btn-outline-primary  btn-sm" style="padding:0 1ch" >Editar</a>
    </div>
    {% endfor %}


{% endfor %}

<br>

<div id="novos">
    <a href="{% url 'core:novo_topico' %}" class="btn btn-success  btn-sm " >Novo Tópico</a>
    <a href="{% url 'core:novo_conteudo' %}" class="btn btn-success  btn-sm" >Novo Conteúdo</a>    
</div>

{% endblock main %}

</body>

</html>

templates/core/index.html
{% extends "layout.html" %}

    {% block main %}
    <article>
        <p>Este website congrega conteúdos desenvolvidos na UC de Complementos de Redes.</p>
        <p>Trata-se de um template. Pode adaptá-lo e modificá-lo totalmente ao seu gosto.</p>  
        <p>Desenvolverá páginas para cada tópico da matéria, apresentando os conceitos teóricos e uma "calculadora" que implemente e permita computar os aspectos apresentados</p>
    </article>
    
    <article>
        {% load static %}
        <img src="{% static 'core\redes.jpg' %}" width="300px" alt="">
    </article>
    {% endblock main %}
    
</body>
</html>

templates/core/novo_conteudo.html
{% extends "layout.html" %}

{% block main %}

    <h3>Novo Conteúdo</h3>

<form action="" method="POST">
    {% csrf_token %}

    <table>
        {{conteudo_form}}
    </table>
    
    <input type="submit" value="Gravar">
</form>

{% endblock main %}

</body>

</html>

templates/core/novo_topico.html
{% extends "layout.html" %}

{% block main %}

    <h3>Novo Tópico</h3>

<form action="" method="POST">
    {% csrf_token %}

    <table>
        {{topico_form}}
    </table>
    
    <input type="submit" value="Gravar">
</form>

{% endblock main %}

</body>

</html>

templates/core/topicos.html
{% extends "layout.html" %}

{% block main %}

<h3>Tópicos abordados</h3>

{% load custom_tags %}

{% for topico in topicos  %}

<h5>{{ topico }} </h5>
<div>
    {% for conteudo in topico.conteudos.all|sort_by:'ordem' %}
    <div class="conteudo"> {{ conteudo }} </div>
    {% endfor %}
</div>

{% endfor %}

<br>

<div id="novos"> 
    <a href="{% url 'core:edita_topicos' %}" class="btn btn-outline-primary  btn-sm" >Edita</a>    
</div>

{% endblock main %}

</body>

</html>

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CoRe</title>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🕸</text></svg>">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">

{% block style %}
      
{% endblock style %}
</head>
<body>
    <header>
        <h1>Complementos de Redes 🕸</h1>
        <p><i>Aplicação que congrega tópicos sobre redes de comunicações</i></p>
        <nav>
            <a href="{% url 'core:index' %}" class="btn btn-primary  btn-sm" >Home</a>
            <a href="{% url 'core:topicos' %}" class="btn btn-warning  btn-sm" >Topicos</a>    
        </nav>
    </header>

    <main>
        <div>
            {% block main %}
      
            {% endblock main %}        
        </div>
    </main>

    <footer>
        Universidade Lusófona @ 2022
    </footer>

</body>
</html>